### ISSUE TITLE
This is incorrect, never have a period with major title on website, only the description text below.

### ISSUE THREAD

**Issue by cryptocc** [expanse-org/expanse-org.github.io#13]
![](https://files.slack.com/files-pri/T08PVQU72-F2P3RHXUJ/screen_shot_2016-10-13_at_1.17.10_pm.png)

This is incorrect, never have a period with major title on website, only the description text below.

**Comment by cryptocc** [comment]
<img width="796" alt="screen shot 2016-10-13 at 1 17 10 pm" src="https://cloud.githubusercontent.com/assets/20465856/19364313/4123a4d4-9153-11e6-8bc5-b02eb6841098.png">

**Comment by chrisfranko** [comment]
fixed
