### ISSUE TITLE
Incorrect, this should be User-Friendly or USER-FRIENDLY

### ISSUE THREAD

**Issue by cryptocc** [expanse-org/expanse-org.github.io#15]
<img width="681" alt="screen shot 2016-10-13 at 1 24 30 pm" src="https://cloud.githubusercontent.com/assets/20465856/19364377/9282bc70-9153-11e6-92b8-e0e3b2a07bef.png">

**Comment by cryptocc** [comment]
USER-FRIENDLY since the others are in caps here

**Comment by chrisfranko** [comment]
got it
