### ISSUE TITLE
I am sure this is known, but if we are linked this we should not have a tiled image like this. Many people have 27" and bigger monitors these days, normal.

### ISSUE THREAD

**Issue by cryptocc** [expanse-org/expanse-org.github.io#16]
People really will take away perceived value if we tile images. Might seem small, but if we can get this non-tiled, as is, way better.

The image is from EXP.life, Github says the image is too big to upload, but you get it, tiled image instead of centered looks bad.

**Comment by chrisfranko** [comment]
I'm going to make a new landing page for it anyways
