### ISSUE TITLE
So, correct exp.life image if possible, it takes away value. DAO goes nowhere, instead, replace with "Coming soon" -- The Borderless link is also broken.

### ISSUE THREAD

**Issue by cryptocc** [expanse-org/expanse-org.github.io#17]
<img width="1250" alt="screen shot 2016-10-13 at 1 35 52 pm" src="https://cloud.githubusercontent.com/assets/20465856/19364660/abc11550-9154-11e6-8751-3af0ce020c8a.png">

**Comment by cryptocc** [comment]
What I mean is, if people click on DAO, maybe something like "coming soon" rather than nothing, nothing looks bad.

**Comment by chrisfranko** [comment]
Do you think the project logos would look better here?
