### ISSUE TITLE
Fix the location of money conf. It should be in MADRID, SPAIN

### ISSUE THREAD

**Issue by omarsiddiqi** [expanse-org/expanse-org.github.io#42]

**Comment by omarsiddiqi** [comment]
![image](https://cloud.githubusercontent.com/assets/6377270/26757818/f3d9415a-4897-11e7-8fe8-e159c2179e95.png)

**Comment by BenazirAshraf** [comment]
![capture](https://cloud.githubusercontent.com/assets/29163968/26760066/e3f69d0a-4928-11e7-9b5b-fd0b9ecae284.JPG)
this has been resolved now.. kindly close this issue

**Comment by omarsiddiqi** [comment]
@BenazirAshraf i wont be closing issues until they are released to prod.
